name: Build and Deploy Spring Boot App using Azure CLI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure App Service using Azure CLI
        run: |
          az webapp deploy \
            --resource-group LoanCalcGroup \
            --name rolva-loanapp \
            --type jar \
            --src-path target/LoanCalculatorApp-1.0.0.jar
